env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - 'airbnb-typescript'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'
  - 'plugin:import/typescript'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
  - 'prettier'
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
  ecmaFeatures:
    jsx: true
plugins:
  - '@typescript-eslint'
  - react
  - 'prettier'
rules:
  '@typescript-eslint/no-shadow': 'off'
  'react/jsx-uses-react': 0
  'react/jsx-uses-vars': 0
  react/jsx-props-no-spreading: 'off'
  script-eslint/no-explicit-any: 'off'
  import/no-cycle: 'off'
  t/prefer-default-export: 'off'
  import/prefer-default-export: 'off'
  react/destructuring-assignment: 'off'
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  '@typescript-eslint/no-explicit-any': 'off'
  '@typescript-eslint/ban-ts-comment': 'off'
  '@typescript-eslint/no-use-before-define': 'off'

settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
      paths:
        - ./src
