name: Bug report
description: Create a report to help us improve tiptap
labels:
  - bug
body:
  - type: textarea
    id: problem
    attributes:
      label: What is the bug you are facing?
      description: A clear and concise description of what the bug is.
      placeholder: "I'm always frustrated when …"
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Which browser was this experienced in? Are any special extensions installed?
      description: Please give us more information about your browser environment so we can reproduce the bug faster. Ex- Browser name, version, extensions, etc.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: How can we reproduce the bug on our side?
      description: Steps to reproduce the behavior
      placeholder: "1. Go to '…' 2. Click on '…' 3. Scroll down to '…' 4. See error"
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: What did you expect to happen?
      description: A clear and concise description of what you expected to happen.
      placeholder: "I expected that clicking the …"
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Useful Details
      description: "Add any other context, screenshots, videos or GIFs here."
  - type: checkboxes
    attributes:
      label: Did you update your dependencies?
      description: "Use `npm update` to update your dependencies."
      options:
        - label: Yes, I’ve updated my dependencies to use the latest version of all packages.
          required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help make Incredible better :heart:
