blank_issues_enabled: false
contact_links:
  - name: Discuss Incredible on GitHub
    url: https://github.com/IncredibledevHQ/Incredible/discussions/new
    about: Join the conversation.
  - name: Join the Incredible Discord
    url: https://discord.gg/jJQWQs8Fh2
    about: Hangout with other Incredible dev and creator's!
