#
# Refer: https://github.com/firebase/firebase-tools
#

name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - develop
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Deploy staging
        run: |
          yarn install --cache-folder .yarncache # Install Dependencies
          yarn codegen # Run GraphQL codegen
          CI=false yarn build # CI=false to ignore warnings
          rm -rf .yarncache
        env:
          NODE_ENV: 'staging'
          HASURA_ADMIN_SECRET: ${{secrets.HASURA_ADMIN_SECRET}}
          VITE_AGORA_APP_ID: ${{secrets.AGORA_APP_ID}}
          VITE_HASURA_SERVER: ${{secrets.HASURA_SERVER}}
          VITE_FIREBASE_CONFIG: ${{secrets.FIREBASE_CONFIG}}
          VITE_SENTRY_DSN: ${{secrets.SENTRY_DSN}}
          VITE_SENTRY_ENABLED: true
          VITE_STORAGE_BASE_URL: ${{ secrets.STORAGE_BASE_URL }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_INCREDIBLEDEV_NEXT_STAGING }}'
          channelId: live
          projectId: incredibledev-next-staging
